[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
nnoremap [denite] <Nop>
nmap <C-f> [denite]
"現在開いているファイルのディレクトリ下のファイル一覧。
nnoremap <silent> [denite]f :<C-u>DeniteBufferDir file/rec -buffer-name=search-buffer-denite<CR>
"バッファ一覧
nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
"レジスタ一覧
nnoremap <silent> [denite]r :<C-u>Denite -buffer-name=register register<CR>
"最近使用したファイル一覧
nnoremap <silent> [denite]z :<C-u>Denite file_mru -buffer-name=search-buffer-denite<CR>

" -buffer-name=
nnoremap <silent> [denite]g :<C-u>Denite grep -buffer-name=search-buffer-denite<CR>
nnoremap <silent> [denite]p :<C-u>Denite -buffer-name=search-buffer-denite -resume<CR>
nnoremap <silent> [denite]i :<C-u>Denite -buffer-name=search-buffer-denite -resume -immediately -cursor-pos=+1<CR>
nnoremap <silent> [denite]o :<C-u>Denite -buffer-name=search-buffer-denite -resume -immediately -cursor-pos=-1<CR>

" Define mappings
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

if executable('rg')
  call denite#custom#var('file/rec', 'command',
     \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'default_opts',
     \ ['-i', '--vimgrep', '--no-heading'])
endif

call denite#custom#filter('matcher/ignore_globs', 'ignore_globs',
     \ [ '.git/', '.ropeproject/', '__pycache__/',
     \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])

'''

[[plugins]]  # w/o neovim
repo = 'roxma/nvim-yarp'

[[plugins]]  # w/o neovim
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]] # mru
repo = 'Shougo/neomru.vim'

[[plugins]] # インデントを見やすく
repo = 'Yggdroot/indentLine'

[[plugins]] # ranger
repo = 'Mizuchi/vim-ranger'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
'''
