[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = "deoplete-plugins/deoplete-jedi"
on_ft = ['python']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_add = '''
let g:jedi#completions_enabled = 0
'''
